# Generated by Django 4.0.2 on 2022-02-03 11:20

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Title')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text')),
                ('photo', models.ImageField(blank=True, upload_to=pages.models.location_image_upload)),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when page was added', verbose_name='Created At')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='Date and time when page was updated', null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'wiki_pages',
            },
        ),
    ]
